/// This class contains all the App Text in String formats.
class TTexts {
  // -- GLOBAL Texts
  static const String and = "and";
  static const String skip = "Skip";
  static const String done = "Done";
  static const String submit = "Submit";
  static const String appName = "PinkRibbon BHC";
  static const String tContinue = "Continue";

  // -- OnBoarding Texts
  static const String onBoardingTitle1 =
      "Learn More About Breast Cancer Symptoms";
  static const String onBoardingTitle2 = "Perform Breast Self-Exam";
  static const String onBoardingTitle3 = "Assess Your Risk of Breast Cancer";

  static const String onBoardingSubTitle1 =
      "Learn about breast cancer symptoms and stay informed!";
  static const String onBoardingSubTitle2 =
      "Empower Yourself - Perform regular breast self-exams to detect any changes early.";
  static const String onBoardingSubTitle3 =
      "Take Control of Your Health - Assess your risk of breast cancer and make informed decisions.";

  // -- Authentication Forms
  static const String firstName = "First Name";
  static const String lastName = "Last Name";
  static const String email = "E-Mail";
  static const String password = "Password";
  static const String newPassword = "New Password";
  static const String username = "Username";
  static const String phoneNo = "Phone Number";
  static const String rememberMe = "Remember Me";
  static const String forgetPassword = "Forget Password?";
  static const String signIn = "Sign In";
  static const String createAccount = "Create Account";
  static const String orSignInWith = "or sign in with";
  static const String orSignUpWith = "or sign up with";
  static const String iAgreeTo = "I agree to";
  static const String privacyPolicy = "Privacy Policy";
  static const String termsOfUse = "Terms of use";
  static const String verificationCode = "verificationCode";
  static const String resendEmail = "Resend Email";
  static const String resendEmailIn = "Resend email in";

  // -- Authentication Headings
  static const String loginTitle = "Welcome back,";
  static const String loginSubTitle =
      "Empowering Women Through Knowledge and Early Detection.";
  static const String signupTitle = "Let’s create your account";
  static const String forgetPasswordTitle = "Forget password";
  static const String forgetPasswordSubTitle =
      "Don’t worry sometimes people can forget too, enter your email and we will send you a password reset link.";
  static const String changeYourPasswordTitle = "Password Reset Email Sent";
  static const String changeYourPasswordSubTitle =
      "Your Account Security is Our Priority! We've Sent You a Secure Link to Safely Change Your Password and Keep Your Account Protected.";
  static const String confirmEmail = "Verify your email address!";
  static const String confirmEmailSubTitle =
      "Congratulations! Your Account Awaits: Verify Your Email to Start Shopping and Experience a World of Unrivaled Deals and Personalized Offers.";
  static const String emailNotReceivedMessage =
      "Didn’t get the email? Check your junk/spam or resend it.";
  static const String yourAccountCreatedTitle =
      "Your account successfully created!";
  static const String yourAccountCreatedSubTitle =
      "Welcome to Your Breast Health Journey: Stay Informed, Stay Empowered!";

  // -- Product
  static const String popularProducts = "Popular Products";

  // -- Home
  static const String homeAppbarTitle = "Welcome Back,";
  static const String homeAppbarSubTitle = "Nur Alya";

  static const String disclaimerRisk =
      "The results generated by this assessment are not a substitute for professional medical advice, diagnosis, or treatment. They are intended to educate and suggest potential risk factors based on your input. \n\nWe strongly encourage you to consult with a healthcare professional for personalized medical advice and any concerns you may have regarding breast health.";
}
